[package]
name = "rs-microservice"
version = "0.1.0"
authors = ["Periklis Tsirakidis <periklis.tsirakidis@holidaycheck.com>"]

[dependencies]
chrono="0.4.2"
futures="*"
tokio-core="*"
futures-await = { git = 'https://github.com/alexcrichton/futures-await' }